sonar.projectKey=node-app-devops
sonar.projectName=node-app-devops
sonar.projectVersion=1.0

sonar.sources=.

sonar.exclusions=node_modules/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
